# Generated by Django 6.0.4 on 2026-04-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitud', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=100)),
                ('tipo_solicitud', models.CharField(choices=[('ACA', 'ACADEMICA'), ('ADA', 'ADMINISTRATIVA'), ('TEC', 'TECNICA'), ('OTR', 'OTRA')], default='ACA', max_length=3)),
            ],
        ),
    ]
